package com.accenture.CustomerIDV.factory;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.sql.DataSource;

public class DBFactory {
	private DataSource dataSource;

	public DataSource getDataSource() {
		return dataSource;
	}

	public void setDataSource(DataSource dataSource) {
		this.dataSource = dataSource;
	}

	public void initialize() {
		DataSource dataSource = getDataSource();
		try {
			Connection connection = dataSource.getConnection();
			Statement statement = connection.createStatement();
			statement
					.executeUpdate("CREATE TABLE VERIFY (QID INTEGER , ANSWER VARCHAR(50) not null, CUSTOMERID INTEGER)");
			statement
					.executeUpdate("CREATE TABLE CUSTOMER (CUSTOMERID INTEGER generated by default as identity (start with 1001) primary key, NAME VARCHAR(50) not null, ADDRESS VARCHAR(50) not null,ACCOUNTTYPE VARCHAR(50) not null)");
			statement
					.executeUpdate("CREATE TABLE ADMIN (USERNAME VARCHAR(50) primary key, PASSWORD VARCHAR(50) not null,LASTLOGIN VARCHAR(50),SESSIONID VARCHAR(50) not null,ISADMIN BOOLEAN)");
			statement
					.executeUpdate("CREATE TABLE USERDETAILS (CUSTOMERID INTEGER foreign key REFERENCES CUSTOMER(CUSTOMERID) , BIRTHDAY VARCHAR(20) not null,PHONENO VARCHAR(10),EMAILID VARCHAR(50) not null,GENDER VARCHAR(10),BALANCE VARCHAR(20) NOT NULL)");
			statement
					.executeUpdate("INSERT INTO ADMIN VALUES('auhpinto','123','','48',true)");
			statement
					.executeUpdate("CREATE TABLE QUESTION (QID INTEGER PRIMARY KEY, QUESTION VARCHAR(500))");
			statement
					.executeUpdate("INSERT INTO QUESTION VALUES(1,'What was the name of your elementary or primary school?')");
			statement
					.executeUpdate("INSERT INTO QUESTION VALUES(2,'In what city or town does your nearest sibling live?')");
			statement
					.executeUpdate("INSERT INTO QUESTION VALUES(3,'What is the name of your paternal or maternal grandmother?')");
			statement
					.executeUpdate("INSERT INTO QUESTION VALUES(4,'What is the name of your first pet?')");
			statement
					.executeUpdate("INSERT INTO QUESTION VALUES(5,'What is the name of place where your spouse was born?')");
			
			statement.close();
			connection.close();
			System.out.println("Database Configured");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}